In [1]:
import numpy as np
import sys

# Basics

### Init of arrays and dimensions

In [97]:
# init array
# you always need to know the shape/size of arr --> welcome back java
init_arr = np.empty(shape=(2,3))
zeros_arr = np.zeros((4,))
ones_arr = np.ones((1,4)).astype(int) # casting 
ones_arr_2d = np.full((2,4), 99).astype(int) # insert 99 to all elements of array
zeros_arr_3d = np.ones((2,4,3), dtype='int16')

random = 10* np.random.rand(2,3)
random_int = np.random.randint(1,25, (2,3))

identity = np.identity(5) # specify only number of rows

# dimension 4, is just a simple 1D list which has 4 elements
# dimension 1,4 is a 2D array which has only one element (another list)
# dimension 2,4 is a 2D array too, but it has 2 rows and 4 element is each col
# dimension x,y,z is a 3D array

print(f'1. {init_arr}')
print(f'Dimensions: {init_arr.ndim}')
print(f'2. {zeros_arr}')
print(f'Dimensions: {zeros_arr.ndim}')
print(f'3. {ones_arr}')
print(f'Dimensions: {ones_arr.ndim}')
print(f'4. {ones_arr_2d}')
print(f'Dimensions: {ones_arr_2d.ndim}')
print(f'5. {zeros_arr_3d}')
print(f'Dimensions: {zeros_arr_3d.ndim}')
print(f'6. {random}')
print(f'7. {random_int}')
print(f'8. {identity}')


1. [[5.47383175 0.15025496 0.4393669 ]
 [9.61020199 0.65741673 0.21588289]]
Dimensions: 2
2. [0. 0. 0. 0.]
Dimensions: 1
3. [[1 1 1 1]]
Dimensions: 2
4. [[99 99 99 99]
 [99 99 99 99]]
Dimensions: 2
5. [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
Dimensions: 3
6. [[7.96475511 1.48647951 2.36218367]
 [4.32440975 9.35204645 4.19366197]]
7. [[22 12 20]
 [ 6  1 18]]
8. [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Shapes and element access

In [42]:
test = np.array([3,2,1,2])
test2d = np.array([[3,2,1,2]])
test3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(f'Shape: {test.shape}')
print(test)
print(f'Shape: {test2d.shape}')
print(test2d)
print(f'Shape: {test3d.shape}')
print(test3d)
print("Element access")
print(test[1])
print(test2d[0][1])
print(test3d[1][0][2])

Shape: (4,)
[3 2 1 2]
Shape: (1, 4)
[[3 2 1 2]]
Shape: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Element access
2
2
9


In [66]:
# you can access elements in numpy way too:
test = np.array([[1,2,3,4],[5,6,7,8]])
print(test)
print(test[1][3])
print(test[1,3]) # this is numpy way!

[[1 2 3 4]
 [5 6 7 8]]
8
8


In [68]:
# get specific row and column
print(test[0,:])
print(test[:,1])

[1 2 3 4]
[2 6]


In [78]:
# [startindex: endindex: step]
test = 10 * np.random.rand(3,6)
print(test)
print(test[0,1:-1:2])

[[3.38755047 8.75279934 8.54343105 1.88299141 7.44615626 3.23708112]
 [6.10513507 5.18654475 6.48847388 2.9021679  3.06891515 4.95689708]
 [8.38351874 5.71431027 8.0717411  9.81527407 3.82080269 3.81456619]]
[8.75279934 1.88299141]


### Change elements

In [89]:
# change element, whole rows/columns and segments
test = 10 * np.random.rand(3,3)
print(test)
print("##################")
test[0,2] = 99
print(test)
print("##################")

# change first row
test[0,:] = [1,2,3]
print(test)
print("##################")      

# change third row but only last 2 elements
test[2,-2:] = [22,33]
print(test)
print("##################")
test[1,:] = [5] # make whole row with 5
print(test)

[[6.1173351  7.53108236 1.97722816]
 [3.60381423 3.09918496 3.08719108]
 [0.72400399 6.72629014 8.79665977]]
##################
[[ 6.1173351   7.53108236 99.        ]
 [ 3.60381423  3.09918496  3.08719108]
 [ 0.72400399  6.72629014  8.79665977]]
##################
[[1.         2.         3.        ]
 [3.60381423 3.09918496 3.08719108]
 [0.72400399 6.72629014 8.79665977]]
##################
[[ 1.          2.          3.        ]
 [ 3.60381423  3.09918496  3.08719108]
 [ 0.72400399 22.         33.        ]]
##################
[[ 1.          2.          3.        ]
 [ 5.          5.          5.        ]
 [ 0.72400399 22.         33.        ]]


#### extend array by same values

In [103]:
arr = np.array([[1,2,3,4]])
arr_row = np.repeat(arr, 3, axis=1)
arr_col = np.repeat(arr, 3, axis=0)
print(arr)
print("##################")
print(arr_row)
print("##################")
print(arr_col)
print("##################")

[[1 2 3 4]]
##################
[[1 1 1 2 2 2 3 3 3 4 4 4]]
##################
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
##################


### Get type and size

In [47]:
# all arrays in numpy are fixed in size and can have only one type
# types
# check https://numpy.org/doc/stable/user/basics.types.html
int_arr = np.array([1,2,3,4])
small_int_arr = np.array([1,2,3,4], dtype='int16')
small_int_arr2 = np.array([1,2,3,4], dtype=np.short)
float_arr = np.array([1.2, 3.4])

print(int_arr.dtype)
print(small_int_arr.dtype)
print(small_int_arr2.dtype)
print(float_arr.dtype)

int64
int16
int16
float64


In [52]:
# size in bytes
print(int_arr.itemsize)
print(small_int_arr.itemsize)
print(float_arr.itemsize)

8
2
8


In [56]:
# total size = num of elements * size of each element (what we get in itemsize)
print(int_arr.size)
print(int_arr.itemsize)
print(int_arr.nbytes)

4
8
32


## Arithmetics

### Basic operations

In [108]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [112]:
arr + 2 # every element will be made +2, works same for all basic operation (*, /, -, //, ** ...)

array([3, 4, 5, 6])

### Arrays operations

In [113]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [116]:
arr1+arr2 # every element multiply with every element, row by row. Works same for all basic operations

array([ 6,  8, 10, 12])

In [117]:
arr_fail = np.array([1,2,3]) # less elements in one arr?
arr1+arr_fail

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## Linear Algebra

In [122]:
arr = np.ones((2,3), dtype="int")
print(arr)
arr2 = np.full((3,2),2)
print(arr2)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


#### matrix multipliction
num of rows in arr == num of cols in arr2

In [124]:
print(arr.shape)
print(arr2.shape)
arr.shape[0] == arr2.shape[1]

(2, 3)
(3, 2)


True

In [125]:
arr * arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [126]:
np.matmul(arr,arr2)

array([[6, 6],
       [6, 6]])

stuff to look at: determinate, inverse, vector decompositiion 
https://numpy.org/doc/stable/reference/routines.linalg.html

## Statisitcs

In [141]:
stats = np.array([[1,2,3,4],[3,5,5,5],[5,6,4,8]])
print(stats)
print(np.min(stats))
print(np.average(stats))

print(np.min(stats, axis=1)) # 0 is column wise and 1 is row wise

[[1 2 3 4]
 [3 5 5 5]
 [5 6 4 8]]
1
4.25
[1 3 4]


for more see https://numpy.org/doc/stable/reference/routines.statistics.html

## Array manupulation and organisation

In [148]:
before = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(before)
print(before.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [149]:
after = before.reshape(2,8)
print(after)
print(after.shape)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
(2, 8)


In [151]:
after_after = before.reshape(2,2,2,2)
print(after_after)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


#### Vertically stacking

In [155]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print("##################")
print(np.vstack([v1,v2,v1]))
print("##################")
print(np.hstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
##################
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
##################
[1 2 3 4 5 6 7 8]


## Other stuff

### Load data from file

In [ ]:
file_data = np.genfromtxt('data.txt', delimiter=',')

### Advanced indexing

In [ ]:
# if in data.txt the value is higher than 50 return true. The return here will be a boolean array
file_data > 50
# access data which is larger than 50
filedata[filedata > 50]

In [156]:
# indexing with array
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,2,8]]

array([1, 3, 9])

In [166]:
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15], [16,17,18,19,20]])
arr3 = np.array([[21,22,23,24,25], [26,27,28,29,30]])

res = np.vstack([arr1,arr2,arr3])
print(res)
# find 11,12,16,17
res[(res > 10) & (res < 18)]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([11, 12, 13, 14, 15, 16, 17])